### ISSUE TITLE
Add highlight for WinSeparator

### ISSUE THREAD

**Issue by ghost** [oahlen/iceberg.nvim#2]
Starting in 0.10, Nvim will be deprecating VertSplit in favor of WinSeparator for window borders. By default WinSeparator will link to Normal, which doesn't look great.

**Comment by oahlen** [comment]
Added dedicated highlight for WinSeparator [4721ec1](https://github.com/oahlen/iceberg.nvim/commit/4721ec1d91968c29c8e3ad71249b5206fdfca6d9)
