### ISSUE TITLE
Removing highlight from line numbers

### ISSUE THREAD

**Issue by sameer1612** [oahlen/iceberg.nvim#4]
Is there a configuration or something that can be passed to remove the light color in gutter area hosting line numbers.
I prefer having a flat look, where it blends with the editor area background color.

Currently:
<img width="607" alt="image" src="https://github.com/oahlen/iceberg.nvim/assets/39580073/2b6eaf16-4836-423e-afab-224563b0e800">

**Comment by sameer1612** [comment]
Solved:
<img width="2168" alt="image" src="https://github.com/oahlen/iceberg.nvim/assets/39580073/be976986-6941-4964-afc3-6cbe1a7f5c1f">

Thanks for the good port pal!

**Comment by Soupertonic** [comment]
How exactly did you achieve that? I'd like to have that too @sameer1612

**Comment by sameer1612** [comment]
> How exactly did you achieve that? I'd like to have that too @sameer1612 

Here's the piece you need to add:

https://github.com/oahlen/iceberg.nvim/issues/4#issuecomment-2212390128
